apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:29d19fecfa661c75596654d162851d2344a5f8374e47a625ddc19d078d2f6ee7
  name: example-registry-quay-openshift-storage.apps.openshift.kreiss.lv/edgars.roze/vote-api
  newName: example-registry-quay-openshift-storage.apps.openshift.kreiss.lv/edgars.roze/vote-api
- digest: sha256:426659fe7225a5a77c2467a7ca78a392e0341ea4aacda43fbbaa1a4c9a1c14e0
  name: example-registry-quay-openshift-storage.apps.openshift.kreiss.lv/edgars.roze/vote-ui
  newName: example-registry-quay-openshift-storage.apps.openshift.kreiss.lv/edgars.roze/vote-ui
